### ISSUE TITLE
"You cannot reuse the ChromeOptions object" error only when running in docker

### ISSUE THREAD

**Issue by ttraxxrepo** [ultrafunkamsterdam/undetected-chromedriver#2001]
I've written a class that automatically starts a new instance (and should be instantiating new chromeOptions) every time the `Bot.run()` command is called

```Python

from seleniumbase import SB

class Bot():
    def run(self):
            with SB(uc=True, user_data_dir=self.user_data_dir_path) as sb:
                  # program code

```

This code works fine when I run it locally in venv, however it does not work when running the same code in a docker container with a mounted /used_data_dir volume (self.user_data_dir_path) for persistency.

Some additional findings I've discovered while testing:

1. In docker, the code works fine for the first run when the user_data_dir does not yet exist
2. In docker, the code works for additional runs leveraging the user_data_dir that gets created from the initial run if the container has not been stopped yet
3. If the container is **restarted** (`docker restart` or `docker stop && docker start`) the code still works
4. Only when the container is **destroyed** and then spun up again (`docker down && docker up`) does the "You cannot reuse the ChromeOptions object" error get thrown

Could you please help me understand why I am experiencing this behavior and how to resolve?

I recognize SeleniumBase is a separate repo I am leveraging, however the maintainer of that repo has sent me here as it seems to be the undetected_chromedriver portion that is throwing the error

Thanks in advance!

Dockerfie:
```Dockerfile
FROM ghcr.io/cascandaliato/seleniumbase:master

# Install necessary packages
RUN apt-get update && \
    apt-get install --yes git ffmpeg

# Copy main application code into the root directory
COPY . /

# Install Python dependencies for the main application
RUN pip install -U pip && pip install -r requirements.txt

ENTRYPOINT ["python3", "main.py"]
```

docker-compose.yml:
```yml
services:
  botscraper:
    container_name: botscraper
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "Python Projects/botscraper/user_data_dir:/user_data_dir"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York
 ```
